num1 = int (input( "please enter first number"))
num2 = int (input( "please enter second number"))

print("your answer is" , num1*num2, "Correct???")

l = int (input( "please enter the length"))
w = int (input( "please enter the width"))
recArea = l * w
print("the area of your rectangle is", recArea)


print("     _______________________________________   ")
print("    |                                       |  ")
print("    | Ottman Elasraoui                      |  ")
print("    | 2385 Falkirk Row                      |  ")
print("    | La Jolla, CA 92037                    |  ")
print("    | Address Line 1                        |  ")
print("    |                                       |  ")
print("    |_______________________________________|  ")                                      

